### ISSUE TITLE
Couldn't able to access http://localhost:8000 API URL

### ISSUE THREAD

**Issue by Navaruban** [harvard-vpal/bridge-adaptivity#206]
I have set adaptive engine project in my local machine successfully. i can able to access Web application from  following URL http://localhost:8008. But i couldn't able to access Web API Project using http://localhost:8000 URL. the following error is displaying. please anyone fix this issue...
![capture3](https://user-images.githubusercontent.com/40147593/51026174-f11c3e00-15b3-11e9-9941-f562a7d4f7f6.PNG)

**Comment by idegtiarov** [comment]
u should use `/api` url instead of `/web/api`
