### ISSUE TITLE
Checking LTI outcome response status

### ISSUE THREAD

**Issue by kunanit** [harvard-vpal/bridge-adaptivity#67]
Probably need to call the function (missing parentheses) in order to check the lms response status:
https://github.com/harvard-vpal/bridge-adaptivity/blob/master/bridge_adaptivity/bridge_lti/outcomes.py#L24
https://github.com/harvard-vpal/bridge-adaptivity/blob/master/bridge_adaptivity/bridge_lti/outcomes.py#L28

Object reference:
https://github.com/pylti/lti/blob/master/src/lti/outcome_response.py#L72

**Comment by idegtiarov** [comment]
That is correct! Will add PR with the fix.
